//
//  HAParamType.h
//  HiAnalytics
//
//  Created by cbg_bigdata on 2020/2/19.
//  Copyright © 2020 cbg_bigdata. All rights reserved.
//

#import <Foundation/Foundation.h>
//Store of the product added to favorites.
static NSString *const kHAParamStoreName = @"$StoreName";

//Brand of the product added to favorites.
static NSString *const kHAParamBrand = @"$Brand";

//Category of the product added to favorites.
static NSString *const kHAParamCategory = @"$Category";

//ID of the product added to the shopping cart.
static NSString *const kHAParamProductId = @"$ProductId";

//Name of the product added to the shopping cart.
static NSString *const kHAParamProductName = @"$ProductName";

//Features of the associated product.
static NSString *const kHAParamProductFeature = @"$ProductFeature";

//Product price.
static NSString *const kHAParamPrice = @"$Price";

//Number of products purchased by a user.
static NSString *const kHAParamQuantity = @"$Quantity";

//Revenue you receive through the transaction.
static NSString *const kHAParamRevenue = @"$Revenue";

//Revenue currency type. This parameter must be used with Revenue.
static NSString *const kHAParamCurrName = @"$CurrName";

//ID of the product location.
static NSString *const kHAParamPlaceId = @"$PlaceId";

//User destination for a hotel reservation.
static NSString *const kHAParamDestination = @"$Destination";

//User check-out date for a hotel reservation.
static NSString *const kHAParamEndDate = @"$EndDate";

//Number of days a user books for a hotel reservation.
static NSString *const kHAParamBookingDays = @"$BookingDays";

//Number of guests a user books for a hotel reservation.
static NSString *const kHAParamPassengersNumber = @"$PassengersNumber";

//Number of rooms a user books for a hotel reservation.
static NSString *const kHAParamBookingRooms = @"$BookingRooms";

//User departure location for a hotel reservation.
static NSString *const kHAParamOriginatingPlace = @"$OriginatingPlace";

//User check-in date for a hotel reservation.
static NSString *const kHAParamBeginDate = @"$BeginDate";

//Transaction ID generated by your transaction system.
static NSString *const kHAParamTransactionId = @"$TransactionId";

//Level of a room booked by a user for a hotel reservation.
static NSString *const kHAParamClass = @"$Class";

//ID generated by the ad network and used to record ad clicks.
static NSString *const kHAParamClickId = @"$ClickId";

//Name of a marketing activity.
static NSString *const kHAParamPromotionName = @"$PromotionName";

//Marketing content of a marketing activity.
static NSString *const kHAParamContent = @"$Content";

//Custom parameter.
static NSString *const kHAParamExtendParam = @"$ExtendParam";

//Name of the creative material used in a marketing activity.
static NSString *const kHAParamMaterialName = @"$MaterialName";

//ID of the slot where a creative material is displayed.
static NSString *const kHAParamMaterialSlot = @"$MaterialSlot";

//Type of the slot where a creative material is displayed, for example, the ad slot, operations slot, or banner..
static NSString *const kHAParamMaterialSlotType = @"$MaterialSlotType";

//Type of a marketing activity, for example, CPC or email.
static NSString *const kHAParamMedium = @"$Medium";

//ID of a marketing activity provider, for example, HUAWEI PPS.
static NSString *const kHAParamSource = @"$Source";

//Search string or keyword.
static NSString *const kHAParamKeywords = @"$Keywords";

//Check-out option entered by a user in the current check-out step.
static NSString *const kHAParamOption = @"$Option";

//Current step of a user in the check-out process.
static NSString *const kHAParamStep = @"$Step";

//Shipping fee generated for the transaction.
static NSString *const kHAParamVirtualCurrName = @"$VirtualCurrName";

//Departure date, hotel check-in date, or lease start date.
static NSString *const kHAParamVoucher = @"$Voucher";

//ID of the product location.
static NSString *const kHAParamPlace = @"$Place";

//Shipping fee generated for the transaction.
static NSString *const kHAParamShipping = @"$Shipping";

//Tax generated for the transaction.
static NSString *const kHAParamTaxFee = @"$TaxFee";

//ID of the user group that a user joins.
static NSString *const kHAParamUserGroupId = @"$UserGroupId";

//Name of a game level.
static NSString *const kHAParamLevelName = @"$LevelName";

//Operation result.
static NSString *const kHAParamResult = @"$Result";

//Role of a user.
static NSString *const kHAParamRoleName = @"$RoleName";

//Game level.
static NSString *const kHAParamLevelId = @"$LevelId";

//Details of the user's comment on an object.
static NSString *const kHAParamDetails = @"$Details";

//Evaluation details, commented object.
static NSString *const kHAParamCommentType = @"$CommentType";

//Indicates the particular method used in an operation. For example, facebook or email in the context of a sign-up or sign-in event.
static NSString *const kHAParamChannel = @"$Channel";

//Score in a game.
static NSString *const kHAParamScore = @"$Score";

//Search string or keyword.
static NSString *const kHAParamSearchKeywords = @"$SearchKeywords";

//Content type selected by a user.
static NSString *const kHAParamContentType = @"$ContentType";

//ID of an achievement.
static NSString *const kHAParamAchievementId = @"$AchievementId";

//Flight number generated by your transaction system.
static NSString *const kHAParamFlightNo = @"$FlightNo";

//Index of a product in the list.
static NSString *const kHAParamPositionId = @"$PositionId";

//Product list displayed to a user.
static NSString *const kHAParamProductList = @"$ProductList";

//User source.
static NSString *const kHAParamRegistMethod = @"$RegistMethod";

//Account type of a user, for example, email or mobile number.
static NSString *const kHAParamAcountType = @"$AcountType";

//Sign-in result.
static NSString *const kHAParamEvtResult = @"$EvtResult";

//Level before the change.
static NSString *const kHAParamPrevLevel = @"$PrevLevel";

//Current level.
static NSString *const kHAParamCurrvLevel = @"$CurrvLevel";

//Reason for changing or canceling an order.
static NSString *const kHAParamReason = @"$Reason";

//Names of vouchers applicable to a product.
static NSString *const kHAParamVouchers = @"$Vouchers";

//Product ID list.
static NSString *const kHAParamListId = @"$ListId";

//Filter condition.
static NSString *const kHAParamFilters = @"$Filters";

//Sorting condition.
static NSString *const kHAParamSorts = @"$Sorts";

//Order ID generated by your transaction system.
static NSString *const kHAParamOrderId = @"$OrderID";

//Payment mode selected by a user.
static NSString *const kHAParamPayType = @"$PayType";

//Expiration time of a voucher.
static NSString *const kHAParamExpireDate = @"$ExpireDate";

//Voucher type.
static NSString *const kHAParamVoucherType = @"$VoucherType";

//Type of a service provided for a user, for example, consultation or complaint.
static NSString *const kHAParamServiceType = @"$ServiceType";

// Game duration.
static NSString *const kHAParamDuration = @"$Duration";

// Top-up entry.
static NSString *const kHAParamPurchaseEntry = @"$PurchaseEntry";

// Game level.
static NSString *const kHAParamLevel = @"$Level";

// Entry.
static NSString *const kHAParamEntry = @"$Entry";

// Props.
static NSString *const kHAParamProps = @"$Props";

// TASKID.
static NSString *const kHAParamTaskId = @"$TaskId";

// Inviter
static NSString *const kHAParamInviter = @"$Inviter";

// User VIP level
static NSString *const kHAParamVIPLevel = @"$VIPLevel";

// First sign-in
static NSString *const kHAParamFirstSignIn = @"$FirstSignIn";

// Discount
static NSString *const kHAParamDiscount = @"$Discount";

// First payment
static NSString *const kHAParamFirstPay = @"$FirstPay";

// Total friends
static NSString *const kHAParamFriendNumber = @"$FriendNumber";

// Group name
static NSString *const kHAParamUserGroupName = @"$UserGroupName";

// Group level
static NSString *const kHAParamUserGroupLevel = @"$UserGroupLevel";

// Total members
static NSString *const kHAParamMembers = @"$Members";

// Level before upgrade
static NSString *const kHAParamLevelBefore = @"$LevelBefore";

// Message type
static NSString *const kHAParamMessageType = @"$MessageType";

// Role combat effectiveness
static NSString *const kHAParamRoleCombat = @"$RoleCombat";

// Top level
static NSString *const kHAParamIsTopLevel = @"$IsTopLevel";

// Occupation
static NSString *const kHAParamRoleClass = @"$RoleClass";

// Skill name
static NSString *const kHAParamSkillName = @"$SkillName";

// Skill level
static NSString *const kHAParamSkillLevel = @"$SkillLevel";

// Level before learning
static NSString *const kHAParamSkillLevelBefore = @"$SkillLevelBefore";

// Gear ID
static NSString *const kHAParamEquipmentId = @"$EquipmentId";

// Gear name
static NSString *const kHAParamEquipmentName = @"$EquipmentName";

// Gear level
static NSString *const kHAParamEquipmentLevel = @"$EquipmentLevel";

// Occupation restrictions
static NSString *const kHAParamClassLimit = @"$ClassLimit";

// Gear level restrictions
static NSString *const kHAParamLevelLimit = @"$LevelLimit";

// Free
static NSString *const kHAParamIsFree = @"$IsFree";

// Total gears
static NSString *const kHAParamTotalAfterChange = @"$TotalAfterChange";

// Gear quality
static NSString *const kHAParamQuality = @"$Quality";

// Enhancement type
static NSString *const kHAParamEnhanceType = @"$EnhanceType";

// New occupation
static NSString *const kHAParamNewClass = @"$NewClass";

// Old occupation
static NSString *const kHAParamOldClass = @"$OldClass";

// Task type
static NSString *const kHAParamTaskType = @"$TaskType";

// Task name
static NSString *const kHAParamTaskName = @"$TaskName";

// Task bonus
static NSString *const kHAParamReward = @"$Reward";

// Activity type
static NSString *const kHAParamActivityType = @"$ActivityType";

// Activity name
static NSString *const kHAParamActivityName = @"$ActivityName";

// Cutscene
static NSString *const kHAParamCutsceneName = @"$CutsceneName";

// Pet ID
static NSString *const kHAParamPetId = @"$PetId";

// Pet name
static NSString *const kHAParamPetDefaultName = @"$PetDefaultName";

// Pet level
static NSString *const kHAParamPetLevel = @"$PetLevel";

// Mount ID
static NSString *const kHAParamMountId = @"$MountId";

// Mount name
static NSString *const kHAParamMountDefaultName = @"$MountDefaultName";

// Mount level
static NSString *const kHAParamMountLevel = @"$MountLevel";

// Server
static NSString *const kHAParamServer = @"$Server";

// First role creation
static NSString *const kHAParamFirstCreate = @"$FirstCreate";

// Gender
static NSString *const kHAParamRoleGender = @"$RoleGender";

// Battle type
static NSString *const kHAParamBattleType = @"$BattleType";

// Battle name
static NSString *const kHAParamBattleName = @"$BattleName";

// Cards in battle
static NSString *const kHAParamNumberOfCards = @"$NumberOfCards";

// Card list in battle
static NSString *const kHAParamCardList = @"$CardList";

// Roles in battle
static NSString *const kHAParamParticipants = @"$Participants";

// Battle difficulty
static NSString *const kHAParamDifficulty = @"$Difficulty";

// MVP
static NSString *const kHAParamMVP = @"$MVP";

// Battle damage
static NSString *const kHAParamDamage = @"$Damage";

// Rankings
static NSString *const kHAParamRanking = @"$Ranking";

// Dungeon
static NSString *const kHAParamDungeonName = @"$DungeonName";

// Reason for earning
static NSString *const kHAParamWinReason = @"$WinReason";

// Virtual balance
static NSString *const kHAParamBalance = @"$Balance";

// Package type
static NSString *const kHAParamPackageType = @"$PackageType";

// Item list
static NSString *const kHAParamItemList = @"$ItemList";

// Gift type
static NSString *const kHAParamGiftType = @"$GiftType";

// Gift name
static NSString *const kHAParamGiftName = @"$GiftName";

// Old value
static NSString *const kHAParamOldValue = @"$OldValue";

// New value
static NSString *const kHAParamNewValue = @"$NewValue";

// Video type
static NSString *const kHAParamVideoType = @"$VideoType";

// Video ID
static NSString *const kHAParamVideoName = @"$VideoName";

// Message title
static NSString *const kHAParamMessageTitle = @"$MessageTitle";

// Response
static NSString *const kHAParamOperation = @"$Operation";

// Drawings
static NSString *const kHAParamNumberOfDrawing = @"$NumberOfDrawing";

// Left pulls for a guaranteed character/item
static NSString *const kHAParamLeftPullsForGuarantee = @"$LeftPullsForGuarantee";

// Role power
static NSString *const kHAParamCombat = @"$Combat";

// Virtual coins
static NSString *const kHAParamAmount = @"$Amount";

// Member type
static NSString *const kHAParamVIPType = @"$VIPType";

// Member status
static NSString *const kHAParamVIPStatus = @"$VIPStatus";

// Member validity period
static NSString *const kHAParamVIPExpireDate = @"$VIPExpireDate";

// Entry
static NSString *const kHAParamEnter = @"$Enter";

// Effective date
static NSString *const kHAParamStartDate = @"$StartDate";

// Validity period
static NSString *const kHAParamEffectiveTime = @"$EffectiveTime";

// Practice name
static NSString *const kHAParamName = @"$Name";

// Practice mode
static NSString *const kHAParamMode = @"$Mode";

// Subject
static NSString *const kHAParamSubject = @"$Subject";

// Accuracy
static NSString *const kHAParamAccuracy = @"$Accuracy";

// Content duration
static NSString *const kHAParamContentLength = @"$ContentLength";

// Description
static NSString *const kHAParamRemark = @"$Remark";

// Name
static NSString *const kHAParamContentName = @"$ContentName";

// Section
static NSString *const kHAParamSection = @"$Section";

// Consecutive check-in days
static NSString *const kHAParamDays = @"$Days";

// Post ID
static NSString *const kHAParamPostId = @"$PostId";

// Operation type
static NSString *const kHAParamType = @"$Type";

// Information
static NSString *const kHAParamInformation = @"$Information";

// Information type
static NSString *const kHAParamInformationType = @"$InformationType";

// Feature
static NSString *const kHAParamFeature = @"$Feature";

// Rooms
static NSString *const kHAParamRooms = @"$Rooms";

// Sale price
static NSString *const kHAParamSalePrice = @"$SalePrice";

// Rent fee
static NSString *const kHAParamRentFee = @"$RentFee";

// Rent type
static NSString *const kHAParamRentType = @"$RentType";

// Equipment attribution series
static NSString *const kHAParamSeries = @"$Series";

// Device model
static NSString *const kHAParamModel = @"$Model";

// Operating device type
static NSString *const kHAParamDeviceType = @"$DeviceType";

// Device name
static NSString *const kHAParamDeviceName = @"$DeviceName";

// Binding duration
static NSString *const kHAParamBindDuration = @"$BindDuration";

// Distributor
static NSString *const kHAParamDealerName = @"$DealerName";

// Appointment arrival time
static NSString *const kHAParamArrivalDate = @"$ArrivalDate";

// Time of occurrence
static NSString *const kHAParamOccurredDate = @"$OccurredDate";

// Purchase type
static NSString *const kHAParamBuyerType = @"$BuyerType";

// Number of seats
static NSString *const kHAParamSeat = @"$Seat";

// Energy type
static NSString *const kHAParamEnergy = @"$Energy";

// Commodity allocation
static NSString *const kHAParamConfiguration = @"$Configuration";

// Select financial scheme
static NSString *const kHAParamIsLoan = @"$IsLoan";

// Name of financial scheme
static NSString *const kHAParamLoanProductName = @"$LoanProductName";

// Financial scheme channel
static NSString *const kHAParamLoanChannel = @"$LoanChannel";

// Repayment method
static NSString *const kHAParamRepaymentMethod = @"$RepaymentMethod";

//  Controller name
static NSString *const kHAParamPageName = @"$PageName";

//
static NSString *const kHAParamAction = @"$Action";

//Page
static NSString *const kHAParamPage = @"$Page";

//Index
static NSString *const kHAParamIndex = @"$Index";

//Module
static NSString *const kHAParamModule = @"$Module";

//Source pageName
static NSString *const kHAParamSourcePageName = @"$SourcePageName";

//City
static NSString *const kHAParamCity = @"$City";

//Departure city
static NSString *const kHAParamFromCity = @"$FromCity";

//Destination city
static NSString *const kHAParamToCity = @"$ToCity";

//Departure date
static NSString *const kHAParamDepartureDate = @"$DepartureDate";

//Return date
static NSString *const kHAParamReturnDate = @"$ReturnDate";

//Trip type
static NSString *const kHAParamTripType = @"$TripType";

//Search hotel
static NSString *const kHAParamSearchHotel = @"$SearchHotel";

//Special ticket
static NSString *const kHAParamSpecialTicket = @"$SpecialTicket";

//HasBaby
static NSString *const kHAParamHasBaby = @"$HasBaby";

//HasChildren
static NSString *const kHAParamHasChildren = @"$HasChildren";

//Country
static NSString *const kHAParamCountry = @"$Country";

//Star
static NSString *const kHAParamStar = @"$Star";

//Checkin date
static NSString *const kHAParamCheckinDate = @"$CheckinDate";

//Checkout date
static NSString *const kHAParamCheckoutDate = @"$CheckoutDate";

//Number of adults
static NSString *const kHAParamAldultCount = @"$AldultCount";

//Baby count
static NSString *const kHAParamBabyCount = @"$BabyCount";

//Children count
static NSString *const kHAParamChildrenCount = @"$ChildrenCount";

//From
static NSString *const kHAParamFrom = @"$From";

//Car mode
static NSString *const kHAParamCarMode = @"$CarMode";

//Car time
static NSString *const kHAParamCarTime = @"$CarTime";

//Flight ID
static NSString *const kHAParamFlightID = @"$FlightID";

//Product
static NSString *const kHAParamProduct = @"$Product";

//Search result
static NSString *const kHAParamSearchResult = @"$SearchResult";

//Departure time
static NSString *const kHAParamDepartureTime = @"$DepartureTime";

//Departure airport
static NSString *const kHAParamDepartureAirport = @"$DepartureAirport";

//Arrive at the airport
static NSString *const kHAParamArriveeAirport = @"$ArriveeAirport";

//Airline
static NSString *const kHAParamAirline = @"$Airline";

//Flight type
static NSString *const kHAParamFlightType = @"$FlightType";

//DirectFlight
static NSString *const kHAParamDirectFlight = @"$DirectFlight";

//Train type
static NSString *const kHAParamTrainType = @"$TrainType";

//Departure station
static NSString *const kHAParamFromStation = @"$FromStation";


//Bed type
static NSString *const kHAParamBedType = @"$BedType";

//Breakfast
static NSString *const kHAParamBreakfast = @"$Breakfast";

//Arrive time
static NSString *const kHAParamArriveTime = @"$ArriveTime";

//Train ID
static NSString *const kHAParamTrainID = @"$TrainID";

//Hotel ID
static NSString *const kHAParamHotelID = @"$HotelID";

//Hotel name
static NSString *const kHAParamHotelName = @"$HotelName";

//TripTag
static NSString *const kHAParamTripTag = @"$TripTag";

//Hotel type
static NSString *const kHAParamHotelType = @"$HotelType";

//Cabin
static NSString *const kHAParamCabin = @"$Cabin";

//Room type
static NSString *const kHAParamRoomType = @"$RoomType";

//Car type
static NSString *const kHAParamCarType = @"$CarType";

//Supplier
static NSString *const kHAParamSupplier = @"$Supplier";

//Student count
static NSString *const kHAParamStudentCount = @"$StudentCount";

//Number of rooms reserved
static NSString *const kHAParamRoomCount = @"$RoomCount";

//Occupancy
static NSString *const kHAParamPersonCount = @"$PersonCount";

//Voucher ID
static NSString *const kHAParamVoucherID = @"$VoucherID";

//Voucher name
static NSString *const kHAParamVoucherName = @"$VoucherName";

//Voucher price
static NSString *const kHAParamVoucherPrice = @"$VoucherPrice";

//User type
static NSString *const kHAParamUserType = @"$UserType";

//Target
static NSString *const kHAParamTarget = @"$Target";

//IsCompeleted
static NSString *const kHAParamIsCompeleted = @"$IsCompeleted";

//User level
static NSString *const kHAParamUserLevel = @"$UserLevel";

//Time
static NSString *const kHAParamTime = @"$Time";

//Distance
static NSString *const kHAParamDistance = @"$Distance";

//Heat consumed
static NSString *const kHAParamCalorieConsumed = @"$CalorieConsumed";

//Source page
static NSString *const kHAParamSourcePage = @"$SourcePage";

//Are there multiple households for one person
static NSString *const kHAParamMultipleAccounts = @"$MultipleAccounts";

//Account type
static NSString *const kHAParamAccountType = @"$AccountType";

//Failure reason
static NSString *const kHAParamFailureReason = @"$FailureReason";

//Authority
static NSString *const kHAParamAuthority = @"$Authority";

//Card type
static NSString *const kHAParamCardType = @"$CardType";

//Issue bank
static NSString *const kHAParamIssueBank = @"$IssueBank";

//Transform amount
static NSString *const kHAParamTransformAmount = @"$TransformAmount";

//Bank name
static NSString *const kHAParamBankName = @"$BankName";

//Source module
static NSString *const kHAParamSourceModule = @"$SourceModule";

//Stock code
static NSString *const kHAParamStockcode = @"$Stockcode";

//Stock name
static NSString *const kHAParamStockname = @"$Stockname";

//Market code
static NSString *const kHAParamMarketCode = @"$MarketCode";

//Market name
static NSString *const kHAParamMarketName = @"$MarketName";

//ViewType
static NSString *const kHAParamViewType = @"$ViewType";

//Trend cycle
static NSString *const kHAParamTrendCycle = @"$TrendCycle";

//Transaction direction
static NSString *const kHAParamTransactionType = @"$TransactionType";

//Currency
static NSString *const kHAParamCurrency = @"$Currency";

//Money
static NSString *const kHAParamMoney = @"$Money";

//Finance Id
static NSString *const kHAParamFinanceId = @"$FinanceId";

//Name of financial product
static NSString *const kHAParamFinanceName = @"$FinanceName";

//Type of financial products
static NSString *const kHAParamFinanceType = @"$FinanceType";

//Expected annualized rate of return
static NSString *const kHAParamFinanceRate = @"$FinanceRate";

//Product term
static NSString *const kHAParamFinanceTimeLimit = @"$FinanceTimeLimit";

//Initial purchase amount
static NSString *const kHAParamFinanceAmountMin = @"$FinanceAmountMin";

//Risk level of financial products
static NSString *const kHAParamFinanceRiskLev = @"$FinanceRiskLev";

//Purchase amount
static NSString *const kHAParamPurchaseAmount = @"$PurchaseAmount";

//Service Charge
static NSString *const kHAParamHandlingFees = @"$HandlingFees";

//Redemption amount
static NSString *const kHAParamRedemptionAmount = @"$RedemptionAmount";

//Service Charge
static NSString *const kHAParamReturnAmount = @"$ReturnAmount";

//Fund code
static NSString *const kHAParamFundCode = @"$FundCode";

//Fund type
static NSString *const kHAParamFundType = @"$FundType";

//Fund name
static NSString *const kHAParamFundName = @"$FundName";

//Risk level
static NSString *const kHAParamFundRiskLev = @"$FundRiskLev";

//Rate
static NSString *const kHAParamChargeRate = @"$ChargeRate";

//Payment method
static NSString *const kHAParamPaymentMethod = @"$PaymentMethod";

//Fixed investment cycle
static NSString *const kHAParamFixedCycle = @"$FixedCycle";

//Entrance
static NSString *const kHAParamEntrance = @"$Entrance";

//code
static NSString *const kHAParamcode = @"$code";

//NewsTopic
static NSString *const kHAParamNewsTopic = @"$NewsTopic";

//Information Source
static NSString *const kHAParamInformationSource = @"$InformationSource";

//Comments Number
static NSString *const kHAParamCommentsNumber = @"$CommentsNumber";

//Forwarding number
static NSString *const kHAParamforwardingNumber = @"$forwardingNumber";

//Likes
static NSString *const kHAParamLikes = @"$Likes";

//Title
static NSString *const kHAParamTitle = @"$Title";

//Departure time
static NSString *const kHAParamArriveDate = @"$ArriveDate";

//Source location
static NSString *const kHAParamSourceLocation = @"$SourceLocation";

//Search type
static NSString *const kHAParamSearchType = @"$SearchType";

//Id
static NSString *const kHAParamId = @"$Id";

//Play mode
static NSString *const kHAParamPlayMode = @"$PlayMode";

//Lists
static NSString *const kHAParamLists = @"$Lists";

//Advertising space
static NSString *const kHAParamAdLocation = @"$AdLocation";

//Advertising classification
static NSString *const kHAParamAdCategory = @"$AdCategory";

//AdTheme
static NSString *const kHAParamAdTheme = @"$AdTheme";

//Progress
static NSString *const kHAParamProgress = @"$Progress";

//Location
static NSString *const kHAParamLocation = @"$Location";

//Rating
static NSString *const kHAParamRating = @"$Rating";

//Performance
static NSString *const kHAParamPerformance = @"$Performance";

//Trading rules
static NSString *const kHAParamTradingRules = @"$TradingRules";

//Portfolio
static NSString *const kHAParamPortfolio = @"$Portfolio";

//Investment manager
static NSString *const kHAParamInvestmentManager = @"$InvestmentManager";

//FundSize
static NSString *const kHAParamFundSize = @"$FundSize";

//ButtonName
static NSString *const kHAParamButtonName = @"$ButtonName";

//UserID
static NSString *const kHAParamUserID = @"$UserID";

//PageCategory
static NSString *const kHAParamPageCategory = @"$PageCategory";

//VipMoney
static NSString *const kHAParamVipMoney = @"$VipMoney";

//VipLocation
static NSString *const kHAParamVipLocation = @"$VipLocation";

//VipLocation
static NSString *const kHAParamVipFailed = @"$VipFailed";

